version: '3.8'
services:
  gateway:
    image: deyeva/credit-conveyor_gateway:1.0.10
    container_name: gateway
    ports:
      - "8080:8080"
  application:
    image: deyeva/credit-conveyor_application:1.0.4
    container_name: application
  conveyor:
    image: deyeva/credit-conveyor_conveyor:1.0.4
    container_name: conveyor
  deal:
    image: deyeva/credit-conveyor_deal:1.0.5
    container_name: deal
    depends_on:
      - deal-db
      - kafka
    links:
      - deal-db
  deal-db:
    image: 'postgres:13.1-alpine'
    container_name: deal-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=credit-conveyor-db
    restart: unless-stopped
  dossier:
    image: deyeva/credit-conveyor_dossier:1.0.6
    container_name: dossier
    depends_on:
      - kafka
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: conveyor-zookeeper
    expose:
      - 2181
  kafka:
    image: wurstmeister/kafka
    container_name: conveyor-kafka
    expose:
      - 9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "conveyor-finish-registration:1:1,conveyor-create-documents:1:1,conveyor-send-documents:1:1,conveyor-send-ses:1:1,conveyor-credit-issued:1:1,conveyor-application-denied:1:1,audit-action:1:1"