spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: dossier
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#  mail:
#    host: smtp.yandex.ru
#    port: 465
#    username: deyevat@yandex.ru
#    password: wxzxtsyxaqfrzmrg
#    properties:
#      mail:
#        smpt:
#          auth: true
#          ssl:
#            enable: true
#          starttls:
#            enable: true

server:
  port: 8083

msa:
  services:
    deal:
      url: http://localhost:8081